services:
  - type: web
    name: hospital-saas-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Hospital_SAAS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        value: base64:7KxWZwMdQC/ZhS9n1rlLSBHaXW+qfage2Ses1UaH+os=
      - key: DB_CONNECTION
        value: sqlite
      - key: PORT
        value: "8000"
      - key: SERVER_NAME
        value: "http://:8000"
      - key: TRUSTED_PROXIES
        value: "*"
